Repository GCWizard/GCWizard, pull requests merged in 2025-01, with the labels that each got.

#2085 Issue 0000 enhance symboly dancing men 3.4.0
  lib/application/i18n/assets/en.json
  lib/application/registry.dart
  lib/tools/symbol_tables/_common/assets/dancing_men_original/config.file
  lib/tools/symbol_tables/_common/assets/dancing_men_original/dancing_men_original.zip
  lib/tools/symbol_tables/_common/assets/dancing_men_original/logo.png
  lib/tools/symbol_tables/_common/assets/dancing_men_v1/dancing_men_v1.zip
  lib/tools/symbol_tables/_common/assets/dancing_men_v1/logo.png
  lib/tools/symbol_tables/_common/assets/dancing_men_v2/config.file
  lib/tools/symbol_tables/_common/assets/dancing_men_v2/dancing_men_v2.zip
  lib/tools/symbol_tables/_common/assets/dancing_men_v2/logo.png
  lib/tools/symbol_tables/_common/assets/dancing_men_v3/dancing_men_v3.zip
  lib/tools/symbol_tables/_common/assets/dancing_men_v3/logo.png
  lib/tools/symbol_tables/_common/assets/dancing_men_v4/dancing_men.zip
  lib/tools/symbol_tables/_common/assets/dancing_men_v4/logo.png
  pubspec.yaml
Labels: feature, Symbol table, User Request

#2094 Several fixes
  lib/tools/general_tools/grid_generator/grid/widget/grid.dart
  lib/tools/general_tools/randomizer/widget/randomizer_letter.dart
  lib/tools/science_and_technology/uic_wagoncode/widget/uic_wagoncode.dart
  lib/utils/variable_string_expander.dart
  test/tools/coords/variable_coordinate/logic/variable_latlon_test.dart
Labels: bug

#2093 Issue 2092 improve binary2image 3.4.0
  lib/application/i18n/assets/en.json
  lib/tools/images_and_files/binary2image/logic/binary2image.dart
  lib/tools/images_and_files/binary2image/widget/binary2image.dart
Labels: enhancement

#2126 Fix Divisor module
  lib/tools/science_and_technology/divisor/logic/divisor.dart
Labels: bug

#2117 MDT: Atomic Numbers
  lib/application/i18n/assets/en.json
  lib/tools/crypto_and_encodings/general_codebreakers/multi_decoder/widget/md_tools.dart
  lib/tools/crypto_and_encodings/general_codebreakers/multi_decoder/widget/multi_decoder.dart
  lib/tools/crypto_and_encodings/general_codebreakers/multi_decoder/widget/tools/md_tool_atomicnumbers_numbers.dart
  lib/tools/science_and_technology/periodic_table/atomic_numbers_to_text/widget/atomic_numbers_to_text.dart
  test/utils/collection_utils_test.dart
Labels: feature
